In [121]:
#import needed modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#  read csv file
df = pd.read_csv('DataAnalyst.csv')
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True

In [4]:
# numbers of rows and columns in df
df.shape

(2253, 16)

In [5]:
# quick information of dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2253 entries, 0 to 2252
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         2253 non-null   int64
 1   Job Title          2253 non-null   object
 2   Salary Estimate    2253 non-null   object
 3   Job Description    2253 non-null   object
 4   Rating             2253 non-null   float64
 5   Company Name       2252 non-null   object
 6   Location           2253 non-null   object
 7   Headquarters       2253 non-null   object
 8   Size               2253 non-null   object
 9   Founded            2253 non-null   int64
 10  Type of ownership  2253 non-null   object
 11  Industry           2253 non-null   object
 12  Sector             2253 non-null   object
 13  Revenue            2253 non-null   object
 14  Competitors        2253 non-null   object
 15  Easy Apply         2253 non-null   object
dtypes: float64(1), int64(2), object(13)
memory usage: 281.8+ KB

In [6]:
# check the columns having null values or not, if yes then count null values
df.isnull().sum()

Unnamed: 0           0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         1
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
Easy Apply           0
dtype: int64

In [9]:
# shows all the columns
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply'],
      dtype='object')

In [11]:
# drop column
df.drop(columns=['Unnamed: 0'],inplace=True)

In [12]:
# show 1st three rows using head method
df.head(3)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1

In [13]:
df['Job Title'].head()

0    Data Analyst, Center on Immigration and Justic...
1                                 Quality Data Analyst
2    Senior Data Analyst, Insights & Analytics Team...
3                                         Data Analyst
4                               Reporting Data Analyst
Name: Job Title, dtype: object

In [19]:
# function to see job titles using list
job_titles = []
def count_posts(dataframe):
    for i in dataframe:
        job_titles.append(i.split(','))

count_posts(df['Job Title'])

In [20]:
job_titles

[['Data Analyst', ' Center on Immigration and Justice (CIJ)'],
 ['Quality Data Analyst'],
 ['Senior Data Analyst', ' Insights & Analytics Team [Customer Operations]'],
 ['Data Analyst'],
 ['Reporting Data Analyst'],
 ['Data Analyst'],
 ['Business/Data Analyst (FP&A)'],
 ['Data Science Analyst'],
 ['Data Analyst'],
 ['Data Analyst', ' Merchant Health'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['DATA ANALYST'],
 ['Senior Data Analyst'],
 ['Investment Advisory Data Analyst'],
 ['Sustainability Data Analyst'],
 ['Data Analyst'],
 ['Clinical Data Analyst'],
 ['DATA PROGRAMMER/ANALYST'],
 ['Data Analyst'],
 ['Product Analyst', ' Data Science'],
 ['Data Science Analyst'],
 ['Data Analyst - Intex Developer'],
 ['Data Analyst'],
 ['Entry Level / Jr. Data Analyst'],
 ['Data Analyst'],
 ['Data + Business Intelligence Analyst'],
 ['Data Analyst', ' Product'],
 ['Data Analyst Entry Level'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Science Analyst', ' Capital Markets'],
 ['Data Analyst (Games)'],
 ['Analyst/Associate Global Markets Credit Data Analyst'],
 ['Data Business Analyst'],
 ['Data Analyst with Excel/DAX/ PowerBI experience- Fulltime'],
 ['Data Science Analyst/Engineer'],
 ['Data Analyst'],
 ['Business Analyst', ' Data Platforms'],
 ['Behavioral Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst -1+ year Contract - NYC'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Advertising Data Analyst'],
 ['Data Analyst'],
 ['Market Data Reporting Analyst'],
 ['Senior Analyst', ' Data Science'],
 ['Senior Data Analyst', ' Disney+'],
 ['Office of the CAO | Reference Data', ' Project Manager/Business Analyst'],
 ['Business Data Analyst'],
 ['Senior Data Analyst'],
 ['Data Scientist / Big Data Analytics Analyst'],
 ['Data Reporting Analyst'],
 ['Principal Data Analyst', ' LATAM - Disney Streaming Services'],
 ['Data Analyst II'],
 ['Data Analyst - Environmental', ' Social', ' and Governance'],
 ['Data Analyst'],
 ['Data Analyst', ' Revenue Analytics'],
 ['Data Analyst - Data Acquisition / Data Lineage'],
 ['Data Analyst - Data Scanning utilizing Rochade'],
 ['Data Analyst - Stitching'],
 ['Junior Data Analyst'],
 ['Data Analyst', ' Retail Media'],
 ['Data Analyst'],
 ['Portfolio Data Analyst'],
 ['Data Science Analyst'],
 ['Data/Reporting Analyst'],
 ['Data Analyst 2'],
 ['Entry Level Data Analyst'],
 ['Marketing Data Analyst'],
 ['Data/Information Mgt Analyst'],
 ['Business Data Analyst'],
 ['Information Systems Officer (Data Analyst)'],
 ['Media Science Big Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data analyst with Python'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Healthcare Data Analyst', ' Qsight'],
 ['BA/Data Analyst'],
 ['Data Analyst Python'],
 ['Data Analyst', ' Bitcoin Trading Firm'],
 ['Data Analyst-BA'],
 ['Data Analytics Solutions Analyst'],
 ['Quantitative Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Descriptive Analytics Data Analyst', ' IB'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Business Data Analyst'],
 ['Data Analyst'],
 ['Healthcare Data Analyst'],
 ['Supply Chain Data Analyst'],
 ['Data Analyst - IBM Tool Set'],
 ['Analyst-Data Integrity'],
 ['Reference Data Operations Analyst - Index Instrument', ' Associate'],
 ['Data Analyst'],
 ['Data & Service Health Analyst'],
 ['Data/Systems Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst Intern'],
 ['Data Analytics Analyst or Associate', ' Cowen Sustainable Investments'],
 ['Data Reporting Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['ERP Data Analyst'],
 ['Data Analyst'],
 ['Healthcare Data/Reporting Analyst'],
 ['PBM Data Analyst'],
 ['Data Analyst (Temporary Assignment)'],
 ['Data Analyst'],
 ['Market Data Analyst'],
 ['Data Analyst'],
 ['Junior Data Analyst'],
 ['Microsoft Dynamics CRM Data Analyst'],
 ['Practice Analyst Data'],
 ['Buyside - Data Scientist/Research Analyst'],
 ['Data Analyst - Healthcare Provider Networks and Formularies'],
 ['Electronic Trading Data Analyst'],
 ['Data Analyst', ' Center for Developing Brain'],
 ['Data Processing & Performance Analyst'],
 ['Business Analyst - Data Analyst'],
 ['Data Analyst with Rochade'],
 ['Advertising Data Analyst'],
 ['Product Analyst - Data'],
 ['Senior Data Analyst'],
 ['Data Analyst'],
 ['Market Research Data Analyst - Physician Technology'],
 ['Data Analyst'],
 ['Look ML Data Analyst'],
 ['Data Collection Analyst'],
 ['Data Analyst'],
 ['DATA ENTRY/ BILLING ANALYST'],
 ['Student Persistence Initiative Data Analyst/Scientist'],
 ['Data Quality Analyst'],
 ['Data Governance Analyst'],
 ['Sr. Business Intelligence Engineer / Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Healthcare Data/Reporting Analyst'],
 ['Data Analyst I - Geriatrics and Palliative Care'],
 ['Data Analyst'],
 ['Data Analyst/Rochade'],
 ['Data Analyst', ' Revenue Analytics'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst II', ' Division of Gastroenterology (Research)'],
 ['Data Analyst', ' Student Success Program'],
 ['Big Data QA Analyst with Jupyter notebook'],
 ['Analyst', ' Data Centers Industry'],
 ['Data Analyst'],
 ['Financial - Data Analyst'],
 ['Data Analyst with Data Scanning and Profiling'],
 ['Business Analyst - Data Governance'],
 ['Senior Data Analyst - Health Economist'],
 ['Lead Data Insights Analyst'],
 ['Research Analyst (Data Science)'],
 ['Data Management Analyst'],
 ['Business Analyst / Data Analyst'],
 ['Healthcare Data/Reporting Analyst'],
 ['Clinical Data Analyst'],
 ['Sr. Data Profiling Analyst'],
 ['Data Analytics Analyst or Associate', ' Cowen Sustainable Investments'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Sr. Data Analyst', ' Revenue Analytics', ' Peacock'],
 ['Senior Data Analyst'],
 ['Data Analyst'],
 ['Senior Data Analyst - Data Cataloging / Data Profiling'],
 ['Data/Report Analyst'],
 ['Senior Data Analyst'],
 ['Human Capital Data Analyst'],
 ['GIS Data analyst'],
 ['Junior Data Analytics Solutions Analyst'],
 ['Data Analyst'],
 ['Data Analyst w/Capital Markets'],
 ['VP', ' Research Project Analyst/Data Management'],
 ['Food Data Analyst'],
 ['Data Management Analyst'],
 ['Data Governance Analyst'],
 ['Data Analyst', ' Enterprise Analytics'],
 ['Data Analytics Solutions Analyst - Mid with Security Clearance'],
 ['Data Analyst Assistant'],
 ['Investment Management Summer Analyst Program - Office of COO: Data & Analytics'],
 ['Data Collection Analyst'],
 ['Data Collection Analyst'],
 ['Sr Business /Data Analyst- Reference data'],
 ['Data Analyst'],
 ['SENIOR DATA ANALYST'],
 ['Senior Data Analyst / Scientist'],
 ['Senior Data Analyst - Regulatory Reporting'],
 ['Data Reporting Analyst'],
 ['Data Governance Analyst'],
 ['Data Analyst'],
 ['Senior Data Analyst (6-12 Month Contract-Remote)'],
 ['Principal Data Analyst', ' LATAM – Disney Streaming Services'],
 ['Data Analyst- Win 10 Migration- NYC'],
 ['Data Analyst (35 hours/week)'],
 ['Tech Business/Data Analyst'],
 ['Data Analyst'],
 ['Senior Data Analyst', ' Financial Services'],
 ['Enterprise Data',
  ' Financial Data Analyst - Content Design Specialist Contractor'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Senior Data Analyst'],
 ['Data Remediation Analyst-EK020719A/JL'],
 ['Business Analyst - Chief Data Office'],
 ['Senior Analyst', ' Data Instrumentation & Quality (Disney+)'],
 ['Sr. Data Analyst'],
 ['Big Data Programmer Analyst'],
 ['Lead Data Analyst'],
 ['Data Analyst'],
 ['Data Governance Analyst'],
 ['Client Service Data Analyst'],
 ['Financial Data Analyst - Accounting - D3529'],
 ['Data / Business Analyst (SQL/Tableau)'],
 ['Data Processing & Performance Analyst New York', ' NY'],
 ['Data Analyst'],
 ['Senior Data Analyst'],
 ['Data Analyst-Junior Profiles also works-Only NY/NJ Candidates Please on w2 Only'],
 ['Business Analyst-Market Data'],
 ['Content Analyst/Data BA-Bus/Tech Strategy - Investment Bank'],
 ['Data Analyst'],
 ['Senior Analyst', ' AB Testing and Data Operations'],
 ['Data Warehouse Analyst'],
 ['Data Analyst I - Geriatrics and Palliative Care'],
 ['Data Analyst'],
 ['Senior Business and Data Analyst'],
 ['Data Analyst II'],
 ['Data Analyst II'],
 ['Data Analyst (35 hours/week)'],
 ['Lead Generation Data Analyst'],
 ['DnA Ambassador (Clinical Business Analyst - Level 1)',
  ' Data & Analytics/Re-post'],
 ['Data Analyst I - Genetics & Genomic Sciences'],
 ['Data Reporting Analyst III'],
 ['Reporting Analyst Data Analyst'],
 ['Data Analyst - CBCH'],
 ['Principal Data Analyst', ' LATAM Disney Streaming Services'],
 ['Data Engineer/Data Analyst'],
 ['Technical Business/Data Analyst'],
 ['CRM Data Performance Analyst'],
 ['eCommerce Data Analyst'],
 ['Senior Data Analyst - Rochade'],
 ['Financial Data Analyst'],
 ['2021 Summer Analyst Program- Data & Analytics Solutions'],
 ['Data Analyst - QC'],
 ['People Operations & Data Analyst'],
 ['Lead Data Analyst (Product)'],
 ['Data Analyst - III'],
 ['SQL Data Analyst'],
 ['Healthcare Data/Reporting Analyst'],
 ['Epic Data Intelligence Analyst'],
 ['JPSC-8461 - Position: 13', '52', '53 Data Analyst'],
 ['Data Analyst - Analytics/SQL'],
 ['Data Analyst-Excel'],
 ['Data Remediation Analyst'],
 ['Data Analyst with Python or Python developer'],
 ['Data Entry Clerk / Data analyst'],
 ['Senior Analyst', ' Data and Insights (Wirecutter)'],
 ['ETL Developer / Data Analyst'],
 ['Big Data Programmer Analyst'],
 ['Data Governance Analyst'],
 ['Data Analyst with Python'],
 ['Data Analyst/Project Manager'],
 ['Data Analyst - Intex Developer'],
 ['Analyst Business Data'],
 ['Sr. Datastage and Data Analyst'],
 ['Programmer Data Analyst'],
 ['Consumer Lending Data Analyst'],
 ['Encounter Data Analyst'],
 ['Business Analyst/PM/Data Analyst - Investment Bank'],
 ['Healthcare Analyst', ' Claims/Encounter Data'],
 ['Data Analyst'],
 ['TX Healthcare Data/Reporting Analyst'],
 ['Senior Data Analyst - Regulatory Reporting'],
 ['Senior Specialist Data Analyst'],
 ['SQL Report Developer Data Analyst'],
 ['Clinical Data Analyst'],
 ['Data Analyst', '', ' Sales Operations - Oracle Data Cloud'],
 ['Data Analyst - Machine Learning'],
 ['Senior Analyst', ' Data Analytics'],
 ['Senior Data Analyst (Product)'],
 ['Senior Data Analyst - Data Cataloging / Data Profiling'],
 ['2021 Summer Analyst Program- Data & Analytics Solutions'],
 ['Technical Data Analyst'],
 ['Senior Analyst', ' Customer Master Data'],
 ['Data Analyst/Project Manager'],
 ['Data Analyst II - Division of Endocrinology'],
 ['Sr. Reference Data Business Analyst - SQL'],
 ['Data Analyst - Actuarial Background'],
 ['Data Management Analyst (ADDM04) SEC SVCS OPS DATA GOVERNANCE - NA'],
 ['BA With Data Analyst Skills'],
 ['Data & Reporting Analyst', ' GNHCC'],
 ['Principal Business Analyst - Data Governance'],
 ['Business Analyst/Data Analyst - Capital Markets'],
 ['.net', ' sharepoint', ' Java', ' Data analyst', ' Business Analyst'],
 ['ETL Datastage Developer/IBM Infosphere Datastage Consultant(ETL Data Analyst)-Only NY/NJ candidates Please'],
 ['Consumer Lending Data Analyst'],
 ['Data Analyst - CBCH'],
 ['Solar Data Analyst'],
 ['Data Science Lead Analyst'],
 ['Clinical Data Analyst'],
 ['Remote: Data Analyst (Data Lineage', ' Financial industry)_Long term'],
 ['Senior Data Analyst'],
 ['Data Governance Analyst'],
 ['Data Management', ' Firmwide Data Quality', ' Analyst'],
 ['Compensation and Data Analyst (Human Resources)'],
 ['Senior Data Analyst'],
 ['Data Analyst II', ' Division of Gastroenterology (Research)'],
 ['NY Healthcare Data/Reporting Analyst'],
 ['Data Analyst'],
 ['Big Data QA Analyst / QA Tester / Test Analyst'],
 ['Senior Data Analyst'],
 ['Senior Supply Chain Data Analyst'],
 ['Data Analyst', ' Capital Markets (Manager)'],
 ['Analyst', ' People Operations & HR Data'],
 ['Senior Analyst', ' Data Instrumentation & Quality (Disney+)'],
 ['CIB F&BM Global Program Management EMEA - International Regulatory - Data Provisioning Business Analyst - Associate'],
 ['Business Data Analyst (Financial Services)'],
 ['Senior IT Technical Data Analyst'],
 ['Data Analyst/Data Acquisition Speciliest with Financial Industry Exp'],
 ['Data Analyst/Data Scanning with Financial Industry exp'],
 ['Sr Business Analyst', ' Data Science'],
 ['Senior Data Analyst - Data Governance'],
 ['Senior Manager', ' Data Analyst'],
 ['Senior Business Intelligence & Data Science Analyst'],
 ['Risk Adjustment Data Analyst'],
 ['Data Analyst III'],
 ['Sr. Data Analyst', ' Retail Media'],
 ['Sr IT Technical Data Analyst'],
 ['Senior Marketing Data Analyst'],
 ['Data Analyst III'],
 ['TX Healthcare Data/Reporting Analyst'],
 ['Senior SQL Data Warehouse Analyst'],
 ['Data Analyst Junior'],
 ['SR. Power BI with DAX - Data Analyst'],
 ['Informatica IDQ - Data Quality Analyst (Contract)'],
 ['Senior Solutions Analyst', ' Data Specialist'],
 ['Operations data analyst'],
 ['HR Data Analyst'],
 ['Healthcare Senior Data Analyst - HEDIS'],
 ['Senior Data Quality Analyst'],
 ['Financial Data Analyst - Accounting ll'],
 ['Data Analyst - Litigation'],
 ['Quantitative Data Analyst/Developer'],
 ['Sr Business Data Analyst SAP', ' SKU', ' Supply Chain'],
 ['Senior Data Analyst', ' Gas Planning and Design Engineering'],
 ['Data Analyst - Cardiac Cath Lab'],
 ['Senior Data Business Analyst'],
 ['Business Analyst/Data Analyst - Capital Markets Data'],
 ['Firmwide Reference Data Operations', ' Pricing Operations', ' Analyst'],
 ['Senior Healthcare Data Analyst'],
 ['Data Analyst', ' Quality & Patient Safety'],
 ['Senior Data Analyst - FHC - Family Support Center'],
 ['QA Data Analyst'],
 ['Sr Data Analyst for Customer Based Management'],
 ['Data Analyst/Project Manager in Jersey City',
  ' New Jersey | Careers at Harborside'],
 ['Senior Financial Analyst - Enterprise Data'],
 ['Data Analyst with Data Lineage/Rochade'],
 ['Senior Market Data Content Acquisition/Procurement Analyst'],
 ['Sr. Specialist Reporting Data Analyst /Engineer - Cloud'],
 ['Senior Business Analyst', ' Data Management'],
 ['Data Science Analyst II - Mount Sinai Health Partners'],
 ['NY Healthcare Data/Reporting Analyst'],
 ['Data Analyst'],
 ['Technical Business Analyst with Retail Banking and Large Data Program'],
 ['Principal Sales Operations Analyst - Oracle Data Cloud'],
 ['QA Production Data Analyst'],
 ['JPSC-7462 - Data Analyst Lead - Sr. Tableau Lead'],
 ['Data Services Lead Analyst'],
 ['Sr Data Analyst', ' Go-Live'],
 ["Data Analyst III- SAS req'd"],
 ['Senior Healthcare Data Analyst'],
 ['Regulatory Risk Management Data Analytics and Reporting Analyst'],
 ['NY Healthcare Data/Reporting Analyst'],
 ['Specialist', ' Data and Reporting Analyst - IT Change Management'],
 ['Datastage Developer/Consultant/IBM Websphere Datastage Developer(ETL Data Analyst)-Only Local to NY/'],
 ["Data Analyst III- SAS req'd"],
 ['Data Warehouse systems analyst'],
 ['TX Healthcare Data/Reporting Analyst'],
 ['NY Healthcare Data/Reporting Analyst'],
 ['Sr. Data Analyst - RWE'],
 ['Data Migration Lead/ Analyst (migration of data to the new target system)'],
 ['Senior Data Analytics Solutions Analyst'],
 ['Technical Analyst - Access/Identity Data Security'],
 ['Data Analyst - Cardiac Cath Lab'],
 ['Data Quality Management Analyst'],
 ['Business Analyst (SQL/SQL TOAD',
  ' Excel',
  ' XML',
  ' X12',
  ' HL7 messaging',
  ' data quality analysis)'],
 ['Senior Teradata Developer / Data Analyst'],
 ['Data & Interface Analyst'],
 ['NY Healthcare Data/Reporting Analyst'],
 ['Healthcare Senior Data Analyst - HEDIS'],
 ['Data Analyst (Must have PL/SQL and Healthcare background)'],
 ['Data Analyst / IT Data & Business Intelligence'],
 ['Sr. Specialist Reporting Data Analyst -Technology'],
 ['Sr. Programmer Analyst - Big Data'],
 ['Senior Data Analyst - FHC - Family Support Center'],
 ['Data Analyst â Junior'],
 ['Sr. Principal Metrics Analyst- Data Scientist'],
 ['Product & Pricing Data Analyst'],
 ['SAP Data Analyst'],
 ['Senior Data Analyst (E-commerce', ' Marketing)'],
 ['Clinical Data Designer (Sr. SDTM Programmer/Analyst)'],
 ['Senior Data Analytics Solutions Analyst with Security Clearance'],
 ['JPSC-7176 - Position 35',
  ' 59',
  ' 62',
  ' 100',
  '101',
  '102',
  ' 141',
  '142',
  '166 : Senior Data Analyst'],
 ['Senior Billing Data Analyst'],
 ['Master Data Analyst'],
 ['Sr. Data Analyst'],
 ['Senior Functional Analyst SAP Data design', ' SD/MM/PP'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Engineer / Data Analyst'],
 ['Junior Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst : 20'],
 ['Data Intelligence - Product Data Quality Analyst (DE - RefData) - Data as a Service'],
 ['Data Engineer/Data Analyst (REMOTE/Eventually Onsite)'],
 ['Data Engineer/Analyst'],
 ['Quality Data Analyst'],
 ['Technical Data Analyst/Architect'],
 ['Data Governance Analyst II'],
 ['Big Data Analyst'],
 ['Senior Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst at Salt Lake City', ' UT'],
 ['Senior Data Analyst'],
 ['Data Scientist/Analyst - Noke'],
 ['Data Analyst - W2 candidate'],
 ['Senior Data Analyst'],
 ['Marketing Coordinator / Data Analyst'],
 ['Senior Data Analyst'],
 ['Financial Data Analyst'],
 ['Special Operations (LREC) Incentives and Proficiency Data Analyst'],
 ['Senior Data Analyst'],
 ['a. Senior Data and Business Analyst'],
 ['Fund Data Analyst'],
 ['Sr Python Data Analyst(no c2c) contract w2 only'],
 ['TX Healthcare Data/Reporting Analyst'],
 ['Data Analyst'],
 ['Data Analyst', ' District Office - Accountability Office'],
 ['Data Analyst (Kings County)'],
 ['Tactical Data Link (TDL) Analyst'],
 ['Data Analyst'],
 ['Data Science Analyst'],
 ['Junior Data Analyst'],
 ['Junior Data Analyst'],
 ['Jr Data Analyst'],
 ['Data Science Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Finance Data Analytics Analyst'],
 ['Business Intelligence/Data Analyst with Security Clearance'],
 ['Research & Data Analyst'],
 ['Metrics & Data Analyst'],
 ['Tactical Data Link (TDL) Analyst-'],
 ['Senior Data Analyst- Secret Clearance-'],
 ['Data Analyst Junior'],
 ['HQ Data Analyst'],
 ['USMTF Data Analyst'],
 ['Mid Data Analyst'],
 ['Product Data Business Analyst'],
 ['Retail Data Quality Analyst'],
 ['USMTF Data Analyst with Security Clearance'],
 ['Senior Data Strategy Analyst (SDSA)'],
 ['Data Analyst - Va Beach - VA with Security Clearance'],
 ['Configuration and Data Management (C&DM) Analyst'],
 ['Jr Management Analyst (Data Management)'],
 ['Senior Data Analyst'],
 ['Tactical Data Link (TDL) Analyst'],
 ['Sr Data Business Analyst - FacilitySource'],
 ['Acoustics Data Analyst/Flight Test Engineer'],
 ['Senior Data Analyst'],
 ['Senior Data Analyst- Secret Clearance'],
 ['Senior Data Management Analyst (SDMA)'],
 ['Data Analyst - Senior Consultant'],
 ['Data Warehouse Programmer/Analyst'],
 ['Data Analyst (Navy) - Mid and Junior Level'],
 ['Data Analyst - Senior Consultant - Norfolk', ' VA with Security Clearance'],
 ['Program Analyst - AIS/Maintenance Data System Coordinator'],
 ['MSC Logistics Data Analyst'],
 ['Data Analyst (Navy) - Mid Level'],
 ['Business Intelligence & Data Analyst'],
 ['Sr Data Business Analyst - FacilitySource'],
 ['Senior Data Analyst (Navy)'],
 ['NIWC Service Desk Analyst Component Enterprise Data Center (CEDC with Security Clearance'],
 ['NIWC Service Desk Analyst Component Enterprise Data Center (CEDC).'],
 ['Junior Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['AvMed Data Governance Analyst'],
 ['Data Management Analyst II'],
 ['Data Analyst Junior'],
 ['Data Analyst â Junior'],
 ['IT Analyst III Data Systems'],
 ['Product Data Analyst'],
 ['Lead Data Analyst'],
 ['Data Analytics Insights Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Product Data & Insights Analyst'],
 ['Survey Data Analyst'],
 ['Senior Data Analyst'],
 ['Data Analyst'],
 ['Data Analyst'],
 ['Data and Policy Analyst - Statistical Programmer'],
 ['Data Analyst'],

In [21]:
df.head(2)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1

In [25]:
# show 1st five rows of 'Salary Estimate' column
df['Salary Estimate'].head()

0    $37K-$66K (Glassdoor est.)
1    $37K-$66K (Glassdoor est.)
2    $37K-$66K (Glassdoor est.)
3    $37K-$66K (Glassdoor est.)
4    $37K-$66K (Glassdoor est.)
Name: Salary Estimate, dtype: object

In [23]:
# last two row data of 'Salary Estimate' column
df['Salary Estimate'].tail(2)

2251    $78K-$104K (Glassdoor est.)
2252    $78K-$104K (Glassdoor est.)
Name: Salary Estimate, dtype: object

In [41]:
# add new column from existing column in df
df['Salary Estimate($)'] = df['Salary Estimate'].apply(lambda x: x[:10])

In [42]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'Easy Apply', 'Salary Estimate($)'],
      dtype='object')

In [43]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Estimate($)
0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,$37K-$66K
1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,$37K-$66K
2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,$37K-$66K
3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,$37K-$66K
4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,$37K-$66K

In [45]:
# drop 'Salary Estimate' column
df.drop(columns=['Salary Estimate'],inplace=True)

In [46]:
df.head(2)

,Job Title,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Estimate($)
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,$37K-$66K
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,$37K-$66K

In [47]:
# view Rating as series
df.Rating

0       3.2
1       3.8
2       3.4
3       4.1
4       3.9
       ...
2248    2.5
2249    2.9
2250   -1.0
2251    3.1
2252    3.4
Name: Rating, Length: 2253, dtype: float64

In [48]:
# see all unique ratings
df.Rating.unique()

array([ 3.2,  3.8,  3.4,  4.1,  3.9,  4.4,  3.7,  4. , -1. ,  3. ,  3.6,
        4.9,  3.3,  3.5,  5. ,  4.8,  4.7,  4.6,  2.9,  1. ,  3.1,  4.5,
        2.3,  4.2,  2.8,  4.3,  2.7,  2.5,  2.6,  2.4,  2. ,  2.1,  1.7,
        2.2,  1.8,  1.6,  1.9])

In [52]:
# function to remove rating below 0
df.Rating = df.Rating.apply(lambda x: x if x >= 0 else 0)

In [53]:
df.Rating.unique()

array([3.2, 3.8, 3.4, 4.1, 3.9, 4.4, 3.7, 4. , 0. , 3. , 3.6, 4.9, 3.3,
       3.5, 5. , 4.8, 4.7, 4.6, 2.9, 1. , 3.1, 4.5, 2.3, 4.2, 2.8, 4.3,
       2.7, 2.5, 2.6, 2.4, 2. , 2.1, 1.7, 2.2, 1.8, 1.6, 1.9])

In [54]:
df.head()

,Job Title,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Estimate($)
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,$37K-$66K
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,$37K-$66K
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,$37K-$66K
3,Data Analyst,Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,$37K-$66K
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,$37K-$66K

In [55]:
df.Founded

0       1961
1       1893
2       2003
3       2002
4       2009
        ...
2248      -1
2249    1935
2250      -1
2251    1984
2252    1864
Name: Founded, Length: 2253, dtype: int64

In [65]:
# function to drop rows having year less then or equal to 0
df.drop(df[df['Founded']<=0].index,inplace=True)

In [66]:
df.Founded.unique()

array([1961, 1893, 2003, 2002, 2009, 2014, 2001, 1914, 1896, 2013, 1841,
       1884, 2004, 2016, 1996, 1958, 2006, 1998, 1969, 2011, 2017, 2005,
       1904, 2018, 1956, 2007, 1990, 1923, 2015, 1951, 1981, 2000, 1966,
       1939, 1999, 1812, 1945, 1985, 1984, 1962, 1995, 2012, 1967, 1799,
       1918, 1948, 1994, 1895, 1845, 1968, 2008, 1911, 1997, 1832, 1934,
       1938, 1963, 1992, 1977, 1886, 1862, 1906, 1993, 1935, 1971, 1989,
       1859, 1946, 1818, 1932, 1784, 1856, 1978, 1912, 1957, 1937, 1982,
       1964, 1850, 1983, 1869, 1947, 1868, 1936, 1853, 2010, 1902, 1944,
       1888, 1880, 1973, 1931, 1987, 2019, 1919, 1979, 1954, 1980, 1976,
       1872, 1926, 1991, 1855, 1959, 1986, 1890, 1882, 1883, 1837, 1817,
       1908, 1988, 1965, 1828, 1889, 1898, 1928, 1913, 1901, 1916, 1857,
       1955, 1949, 1970, 1822, 1972, 1864, 1975, 1960, 1885, 1922, 1740,
       1830, 1887, 1974, 1905, 1953, 1952, 1897, 1865, 1921, 1867, 1933,
       1874, 1891, 1807, 1870, 1892, 1852, 1698, 1924, 1907, 1682, 1875,
       1917, 1876, 1785, 1909, 1789, 1930], dtype=int64)

In [67]:
df.shape

(1593, 15)

In [68]:
df.head()

,Job Title,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Estimate($)
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,$37K-$66K
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,$37K-$66K
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1,$37K-$66K
3,Data Analyst,Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1,$37K-$66K
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,$37K-$66K

In [82]:
# function to remove 'employees' sufix from our columns data
df['Size'] = df['Size'].apply(lambda x : x[:-10])

In [83]:
df.Size.values

array(['201 to 500', '10000+', '1001 to 5000', ..., '10000+',
       '201 to 500', '10000+'], dtype=object)

In [122]:
#  function to remove 'to' substring and replace it with '-' symbol in df
df['Size'] = df['Size'].apply(lambda x : ('-').join(x.split('to')))

In [89]:
df.Size

0         201 - 500
1            10000+
2       1001 - 5000
3         201 - 500
4        501 - 1000
           ...
2243         10000+
2245    1001 - 5000
2249         10000+
2251      201 - 500
2252         10000+
Name: Size, Length: 1593, dtype: object

In [90]:
df.head(2)

,Job Title,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Estimate($)
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 - 500,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,$37K-$66K
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1,$37K-$66K

In [100]:
df['Easy Apply'].unique()

array(['True', '-1'], dtype=object)

In [105]:
# replace outlier with boolean values
df['Easy Apply'].replace({'-1':False,'True':True}, inplace=True)

In [106]:
df['Easy Apply'].unique()

array([ True, False])

In [107]:
df.head()

,Job Title,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Estimate($)
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 - 500,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True,$37K-$66K
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,False,$37K-$66K
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 - 5000,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,False,$37K-$66K
3,Data Analyst,Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 - 500,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,False,$37K-$66K
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 - 1000,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,$37K-$66K

In [109]:
df.Competitors.unique()

array(['-1', 'GoDaddy', 'DraftKings', 'Travelers, Chubb, Crum & Forster',
       'Thomson Reuters, Hearst, Pearson', 'Signifyd, Forter',
       'NewYork-Presbyterian Hospital, Northwell Health',
       'DoubleClick, Specific Media, Collective',
       'KPMG, Accenture, Deloitte', 'Microsoft, Apple, Facebook',
       'Goldman Sachs, Commonwealth Bank of Australia, Deutsche Bank',
       'Hired, Indeed, AngelList', 'Criteo, AppNexus, dataxu',
       'News Corp, WarnerMedia, NBCUniversal',
       'Soros Fund Management, D. E. Shaw & Co. - Investment Firm, Fortress Investment Group',
       'Persistent Systems (India), GlobalLogic, Synechron',
       'Google, Goldman Sachs, Thomson Reuters',
       'MediaMath, Conversant, AppNexus',
       'Fidelity Investments, BlackRock, Putnam Investments',
       'Artech Information Systems, Mindlance, Tech Mahindra',
       'Coleman Research, AlphaSights, Third Bridge',
       'Deloitte, Huron Consulting Group, Point B',
       'TEKsystems, Insight Global, Accenture',
       'Jefferies, Piper Sandler, FBR', 'Adecco, Manpower',
       'Ibotta, GutCheck', 'Accenture, CGI, Sopra Steria',
       'Amazon, Accenture, Microsoft',
       'Catholic Health System, NewYork-Presbyterian Hospital', 'RBC',
       'Sky Betting & Gaming', 'IQVIA, GlobalData',
       'Google, Microsoft, Walmart', 'Honor, HomeHero',
       'Gartner, Forrester, IDC',
       'Edelman, Burson-Marsteller, FleishmanHillard',
       'Deutsche Bank, Credit Suisse, Morgan Stanley',
       'Appen, Lionbridge',
       'Beacon Hill Staffing Group, PageGroup, Solomon Page',
       'Activision Blizzard, Electronic Arts',
       'Capgemini, Accenture, Deloitte', 'G4S, Loomis, GardaWorld',
       'Northwell Health, Stony Brook University Medical, Catholic Health Services of Long Island',
       'Morgan Stanley, Goldman Sachs',
       'UnitedHealth Group, Cigna, Aetna',
       'State Street, Northern Trust, BlackRock',
       'Mindlance, Artech Information Systems, Pyramid Consulting',
       'EmblemHealth, UnitedHealth Group, Aetna',
       'SAP, Salesforce, Microsoft',
       'Teva Pharmaceuticals, Sandoz International, Perrigo',
       'Bank Of Tokyo-Mitsubishi UFJ, Mizuho Financial Group, Citi',
       'RELX', 'Sunrun, Vivint Solar, Trinity Solar',
       'Fastaff, Kaiser Permanente, American Traveler',
       'Infosys, Cognizant Technology Solutions, Tata Consultancy Services',
       'Accenture, IBM, Capgemini',
       'H&R Block, Liberty Tax Service, Intuit',
       'LabCorp, Bio-Reference Labs, Thermo Fisher Scientific',
       'Northeast Utilities', 'Arbella Insurance, Safety Insurance',
       'Kelly',
       'Atlantic Health System, Robert Wood Johnson University Hospital, Solaris Health System',
       'TEKsystems, Randstad US',
       'Collabera, Artech Information Systems, TEKsystems',
       'J.P. Morgan, Merrill Lynch, Morgan Stanley',
       'Citrix, VMware, Juniper Networks',
       'General Dynamics Information Technology, ENSCO, Booz Allen Hamilton',
       'Prescription Lifeline', 'JBS USA Holdings, Tyson Foods, Hormel',
       'Accenture, Deloitte, PwC', 'CSC, ManTech, SAIC',
       'First Service Networks, SMS Assist, Vixxo',
       'Pitney Bowes, US Postal Service, Envelope Manager Software',
       'Adobe, Akamai, Oracle', 'Acumen', 'Experis',
       'UCLA Health, City of Hope, Keck Medicine of USC',
       'DPR Construction, Webcor', 'Cyient',
       'PIMCO, TCW, Oaktree Capital Management', 'Netflix, Amazon, Apple',
       'NBCUniversal', 'Riot Games, Google, Activision Blizzard',
       'Walt Disney Company, NBCUniversal',
       'Kaiser Permanente, CVS Health, Walgreens',
       'Health Net, Kaiser Permanente, Molina Healthcare',
       'Chegg, Tutor.com, Smarthinking',
       'Activision, Riot Games, Electronic Arts',
       'Cedars-Sinai Medical Center, Loma Linda University Health, Harbor Hospital',
       'HCA Healthcare, Dignity Health, Sutter Health',
       'East West Bank, Bank of the West, First Republic Bank',
       'Kforce, NTT DATA, IBM', 'CyberCoders, Kforce, ASGN Incorporated',
       'OpenSymmetry, Perficient, DataClarity',
       'Google, Microsoft, Samsung Electronics',
       'AutoZone, eBay, Advance Auto Parts',
       'Procter & Gamble, Nestlé, Johnson & Johnson',
       'John Deere, Bobcat Company', 'Kelly, Manpower',
       'Adventist Health, Providence Health & Services',
       'J.P. Morgan, Bank of America', 'Accenture, West Monroe, Slalom',
       'eHealth, Anthem', 'Adecco, ManpowerGroup, Allegis Corporation',
       'Anheuser-Busch InBev, The Boston Beer Company',
       'Cerner, Epic, Athena Health Care Systems',
       'Redwood Logistics, Coyote Logistics, Echo Global Logistics',
       'Robert Half, Insight Global',
       'Continental, FCA Fiat Chrysler Automobiles',
       'J.P. Morgan, Bank of America, U.S. Bank',
       'Stanley Black & Decker, Milwaukee Tool',
       'BlackRock, Nuveen, Piper Sandler', 'CIBC, RBC, TD',
       'Cognizant Technology Solutions, Infosys, Wipro',
       'International Paper, Graphic Packaging International, Smurfit Kappa',
       'Capgemini, Slalom, Accenture', 'Avant, Enova, OppLoans',
       'Blue Yonder, SAP, NCR', 'Deloitte, KPMG, PwC',
       'Nielsen, Kantar, IRI',
       'Wolverine Trading, Interactive Brokers, Citadel',
       'Aon, Accenture, Marsh & McLennan Companies',
       'Kearney, AlixPartners, Hitachi Consulting',
       'HCA Healthcare, Vanguard Health Systems',
       'Cisco Systems, Huawei Technologies, IBM',
       'CVS Health, Target, Walmart',
       'Converge, Future Electronics, Advanced MP Technology',
       'American Tower, SBA Communications, TowerCo LLC',
       'Carr Riggs & Ingram, Cherry Bekaert, LBMC',
       'Transnational Foods, One Source Distributors',
       'Fiserv, First Data, Jack Henry & Associates',
       'Booz Allen Hamilton, Abt Associates, Oliver Wyman',
       'Anthem, Molina Healthcare, Humana',
       'Kforce, PageGroup, Robert Half',
       'DP Electric, Helix Electric, Wilson Electric', 'Adecco, Kforce',
       'Big O Tires, Les Schwab Tire Centers, Pep Boys',
       'Harris, Gogo, Inmarsat', 'TEKsystems, Aerotek',
       'Advance Auto Parts, AutoZone, NAPA Auto Parts',
       'Charles Schwab, Fidelity Investments, Edward Jones',
       'ComforceHealth, TEKsystems, Allegis Group',
       'GEICO, Allstate, State Farm',
       'NEXTGEN GLOBAL RESOURCES, Wavsys, TEKsystems',
       'MATRIX Resources, The Insource Group, TEKsystems',
       'Walmart, Walgreens, Express Scripts',
       'DrugDev , Bracket, Bioclinica', 'Covance, ICON',
       'Kforce, Insight Global, Volt Consulting Group',
       'Harvard University, Yale University, Princeton University',
       'UnitedHealth Group, Molina Healthcare, Centene',
       'Thermo Fisher Scientific, MilliporeSigma, Merck KGaA', 'Vaptech',
       'The Judge Group, Addison Group, PageGroup',
       'Chase, BB&T, SunTrust',
       'Lockheed Martin, Northrop Grumman, Airbus',
       'TEKsystems, CGI, SDLC Partners',
       'PathFinder Staffing, Juno Search Partners, Robert Half',
       'Aerotek, Kforce, Glotel', 'Pfizer, AstraZeneca, Merck',
       'Penn Medicine, Kimmel Cancer Center Jefferson, Abington Jefferson Health',
       'General Dynamics, Lockheed Martin',
       'BAE Systems USA, CACI International, General Dynamics Information Technology',
       'Infosys, Tata Consultancy Services, Wipro',
       'PetSmart, Walmart, Costco Wholesale',
       'Booz Allen Hamilton, Noblis, Deloitte',
       'SAIC, Leidos, Northrop Grumman',
       'Chenega Corporation, Chugach Alaska, ASRC Federal Holding Company',
       'PRA Group', 'Cornerstone OnDemand, Blackboard',
       'Sharp HealthCare, Scripps Health',
       'PRA Group, PRA Group (Canada)', 'Thermo Fisher Scientific, Roche',
       'Medtronic, Roche', 'Abbott, Siemens, Baxter', 'Biogen',
       'Square, PayPal, H&R Block',
       'Viejas Casino, Barona Casino, Pechanga Resort & Casino',
       'Forsythe Technology, ePlus', 'CDW, PCM, SHI International',
       'Tyler Technologies', 'ALDI, Tesco, Carrefour',
       'Accenture, Capgemini',
       'Ericsson-Worldwide, Huawei Technologies, Microsoft',
       'Kforce, Mitchell Martin, Insight Global',
       'FDIC, Office of the Comptroller of the Currency, SEC',
       'GATX, BNSF Railway', 'Infosys, Accenture, Capgemini',
       'Palo Alto Networks, NortonLifeLock, CrowdStrike',
       'Yardi Systems, AppFolio',
       'Marketing Werks, GMR Marketing, Anderson Merchandisers',
       'Arena, HCL Technologies, PTC',
       'Vivint Smart Home, Johnson Controls',
       'Mortgage Connect, Amrock, Title365',
       'SPX, Flowserve, Robbins & Myers',
       'Edelman, Burson-Marsteller, Weber Shandwick', 'Orthofix, Stryker',
       'Alliance Residential, Wood Partners, Trammell Crow Residential',
       'Avant, LendingClub, Prosper.com',
       'AIR Worldwide, EQECAT, Verisk Analytics',
       'Audi, BMW, Mercedes-Benz International',
       'TEKsystems, Collabera, Artech Information Systems',
       'STMicroelectronics, Fairchild Semiconductor, Infineon Technologies',
       'Insight Global, Pyramid Consulting, MATRIX Resources',
       'Salesforce, Oracle, Microsoft',
       'Mindtree, Happiest Minds Technologies, Altran Americas',
       'Mentor Graphics, Synopsys',
       'TEKsystems, Artech Information Systems, PDS Tech',
       'World Wide Technology, Astreya Partners, Taos',
       'Amgen, Baxter, Bristol Myers Squibb',
       'Optimal Solutions Integration, Capgemini',
       'TEKsystems, Akraya, Intelliswift', 'Amazon, Best Buy, Apple',
       'Skytron, STERIS, Hill-Rom', 'Chegg, StudyBlue',
       'Sutter Health, UCSF Medical Center and UCSF Benioff Children’s Hospitals, Kaiser Permanente',
       'InsWeb, Insure.com, Answer Financial', 'Aquent, 24 Seven Talent',
       'Palo Alto Networks, FireEye, Juniper Networks',
       'Lionbridge, SDL, TransPerfect',
       'Illumina, Thermo Fisher Scientific, Oxford Nanopore Technologies',
       'Nektar Therapeutics, Gilead Sciences, Theravance',
       'Amazon, Apple', 'Zocdoc, Sapphire Digital', 'OneSignal', 'Epic',
       'Interpublic Group, Omnicom, WPP', 'Bloomreach',
       'Google, Microsoft, Apple', 'Intuit',
       'Attain, Deloitte, Booz Allen Hamilton',
       'Boeing, Northrop Grumman, Raytheon Technologies',
       'American Eagle Outfitters, Ralph Lauren, J. Crew',
       'Aerotek, WinterWyman, Hollister Staffing', 'Robert Half, Kforce',
       'Cognizant Technology Solutions, EY, McKinsey & Company',
       'Accenture, IBM, Infosys',
       'Cognizant Technology Solutions, Accenture, IBM',
       'TireHub, National Tire Warehouse, Dealer Tire',
       'TEKMARK Global Solutions, Marlabs, IBM',
       'Intercontinental Exchange, Euronext, Nasdaq',
       'The Home Depot, Amazon, Walmart',
       'Midas, Monro Auto Service and Tire Centers',
       'C.H. Robinson, Transplace',
       'Blizzard Entertainment, Riot Games, Electronic Arts', 'LinkedIn',
       'Pusher, Firebase', 'Amazon, Google, Microsoft',
       'Paxata, Datameer, Informatica', 'UserZoom, Validately',
       'Stanford Health Care, Dignity Health, Sutter Health',
       'Zillow, Trulia, Coldwell Banker', 'Facebook, Google, Pinterest',
       'Silicon Valley Bank, City National Bank (Texas)',
       'Illumina, Agilent Technologies, Roche',
       'NortonLifeLock, McAfee, Verisign',
       'Collabera, Mitchell Martin, The Judge Group',
       'Bank of America, Wells Fargo, U.S. Bank',
       'Thermo Fisher Scientific, Abbott, Ortho Clinical Diagnostics',
       'Redis Labs, GridGain', 'Nurx', 'Fidelity Investments, Vanguard',
       'Kaiser Permanente, UC Davis Health, Dignity Health',
       'Mu Sigma, ZS Associates, Fractal', 'Accenture, Deloitte, IBM',
       'Spectrum Brands, Scotts Miracle-Gro, Newell Brands',
       'CUNA Mutual, SWBC, Overby-Seawell',
       'Apex Systems, Kforce, Robert Half', 'Lionbridge, Pole To Win',
       'DHL Global Forwarding, Freight, DB Schenker, Panalpina',
       'SDL, Keywords Studios, TransPerfect', 'Google, Amazon, Apple',
       "Sam's Club, BJ's Wholesale Club", 'Zillow, Trulia',
       'WeDo technologies, Intec Telecom, Amdocs',
       "Seattle Children's, Center for Infectious Disease Research, University of Washington",
       'Cognizant Technology Solutions, Tata Consultancy Services, Accenture',
       'Equinix, Digital Realty, CyrusOne',
       'Cognizant Technology Solutions, Infosys, HCL Technologies',
       'Morningstar, Value Line, Bankrate',
       'Checkout 51, RetailMeNot, shopkick',
       'BNY Mellon, DTCC, Computershare', 'Lennar, Meritage Homes',
       'Randstad, Kelly', 'AT&T, Verizon', 'Premier, Inc., Vizient',
       'Avnet, Ingram Micro, Tech Data',
       'Centura Health, HealthONE, Denver Health and Hospital Authority'],
      dtype=object)

In [114]:
df.Competitors.replace({'-1':'No Compititors'},inplace=True)

In [115]:
df.Competitors.unique()

array(['No Compititors', 'GoDaddy', 'DraftKings',
       'Travelers, Chubb, Crum & Forster',
       'Thomson Reuters, Hearst, Pearson', 'Signifyd, Forter',
       'NewYork-Presbyterian Hospital, Northwell Health',
       'DoubleClick, Specific Media, Collective',
       'KPMG, Accenture, Deloitte', 'Microsoft, Apple, Facebook',
       'Goldman Sachs, Commonwealth Bank of Australia, Deutsche Bank',
       'Hired, Indeed, AngelList', 'Criteo, AppNexus, dataxu',
       'News Corp, WarnerMedia, NBCUniversal',
       'Soros Fund Management, D. E. Shaw & Co. - Investment Firm, Fortress Investment Group',
       'Persistent Systems (India), GlobalLogic, Synechron',
       'Google, Goldman Sachs, Thomson Reuters',
       'MediaMath, Conversant, AppNexus',
       'Fidelity Investments, BlackRock, Putnam Investments',
       'Artech Information Systems, Mindlance, Tech Mahindra',
       'Coleman Research, AlphaSights, Third Bridge',
       'Deloitte, Huron Consulting Group, Point B',
       'TEKsystems, Insight Global, Accenture',
       'Jefferies, Piper Sandler, FBR', 'Adecco, Manpower',
       'Ibotta, GutCheck', 'Accenture, CGI, Sopra Steria',
       'Amazon, Accenture, Microsoft',
       'Catholic Health System, NewYork-Presbyterian Hospital', 'RBC',
       'Sky Betting & Gaming', 'IQVIA, GlobalData',
       'Google, Microsoft, Walmart', 'Honor, HomeHero',
       'Gartner, Forrester, IDC',
       'Edelman, Burson-Marsteller, FleishmanHillard',
       'Deutsche Bank, Credit Suisse, Morgan Stanley',
       'Appen, Lionbridge',
       'Beacon Hill Staffing Group, PageGroup, Solomon Page',
       'Activision Blizzard, Electronic Arts',
       'Capgemini, Accenture, Deloitte', 'G4S, Loomis, GardaWorld',
       'Northwell Health, Stony Brook University Medical, Catholic Health Services of Long Island',
       'Morgan Stanley, Goldman Sachs',
       'UnitedHealth Group, Cigna, Aetna',
       'State Street, Northern Trust, BlackRock',
       'Mindlance, Artech Information Systems, Pyramid Consulting',
       'EmblemHealth, UnitedHealth Group, Aetna',
       'SAP, Salesforce, Microsoft',
       'Teva Pharmaceuticals, Sandoz International, Perrigo',
       'Bank Of Tokyo-Mitsubishi UFJ, Mizuho Financial Group, Citi',
       'RELX', 'Sunrun, Vivint Solar, Trinity Solar',
       'Fastaff, Kaiser Permanente, American Traveler',
       'Infosys, Cognizant Technology Solutions, Tata Consultancy Services',
       'Accenture, IBM, Capgemini',
       'H&R Block, Liberty Tax Service, Intuit',
       'LabCorp, Bio-Reference Labs, Thermo Fisher Scientific',
       'Northeast Utilities', 'Arbella Insurance, Safety Insurance',
       'Kelly',
       'Atlantic Health System, Robert Wood Johnson University Hospital, Solaris Health System',
       'TEKsystems, Randstad US',
       'Collabera, Artech Information Systems, TEKsystems',
       'J.P. Morgan, Merrill Lynch, Morgan Stanley',
       'Citrix, VMware, Juniper Networks',
       'General Dynamics Information Technology, ENSCO, Booz Allen Hamilton',
       'Prescription Lifeline', 'JBS USA Holdings, Tyson Foods, Hormel',
       'Accenture, Deloitte, PwC', 'CSC, ManTech, SAIC',
       'First Service Networks, SMS Assist, Vixxo',
       'Pitney Bowes, US Postal Service, Envelope Manager Software',
       'Adobe, Akamai, Oracle', 'Acumen', 'Experis',
       'UCLA Health, City of Hope, Keck Medicine of USC',
       'DPR Construction, Webcor', 'Cyient',
       'PIMCO, TCW, Oaktree Capital Management', 'Netflix, Amazon, Apple',
       'NBCUniversal', 'Riot Games, Google, Activision Blizzard',
       'Walt Disney Company, NBCUniversal',
       'Kaiser Permanente, CVS Health, Walgreens',
       'Health Net, Kaiser Permanente, Molina Healthcare',
       'Chegg, Tutor.com, Smarthinking',
       'Activision, Riot Games, Electronic Arts',
       'Cedars-Sinai Medical Center, Loma Linda University Health, Harbor Hospital',
       'HCA Healthcare, Dignity Health, Sutter Health',
       'East West Bank, Bank of the West, First Republic Bank',
       'Kforce, NTT DATA, IBM', 'CyberCoders, Kforce, ASGN Incorporated',
       'OpenSymmetry, Perficient, DataClarity',
       'Google, Microsoft, Samsung Electronics',
       'AutoZone, eBay, Advance Auto Parts',
       'Procter & Gamble, Nestlé, Johnson & Johnson',
       'John Deere, Bobcat Company', 'Kelly, Manpower',
       'Adventist Health, Providence Health & Services',
       'J.P. Morgan, Bank of America', 'Accenture, West Monroe, Slalom',
       'eHealth, Anthem', 'Adecco, ManpowerGroup, Allegis Corporation',
       'Anheuser-Busch InBev, The Boston Beer Company',
       'Cerner, Epic, Athena Health Care Systems',
       'Redwood Logistics, Coyote Logistics, Echo Global Logistics',
       'Robert Half, Insight Global',
       'Continental, FCA Fiat Chrysler Automobiles',
       'J.P. Morgan, Bank of America, U.S. Bank',
       'Stanley Black & Decker, Milwaukee Tool',
       'BlackRock, Nuveen, Piper Sandler', 'CIBC, RBC, TD',
       'Cognizant Technology Solutions, Infosys, Wipro',
       'International Paper, Graphic Packaging International, Smurfit Kappa',
       'Capgemini, Slalom, Accenture', 'Avant, Enova, OppLoans',
       'Blue Yonder, SAP, NCR', 'Deloitte, KPMG, PwC',
       'Nielsen, Kantar, IRI',
       'Wolverine Trading, Interactive Brokers, Citadel',
       'Aon, Accenture, Marsh & McLennan Companies',
       'Kearney, AlixPartners, Hitachi Consulting',
       'HCA Healthcare, Vanguard Health Systems',
       'Cisco Systems, Huawei Technologies, IBM',
       'CVS Health, Target, Walmart',
       'Converge, Future Electronics, Advanced MP Technology',
       'American Tower, SBA Communications, TowerCo LLC',
       'Carr Riggs & Ingram, Cherry Bekaert, LBMC',
       'Transnational Foods, One Source Distributors',
       'Fiserv, First Data, Jack Henry & Associates',
       'Booz Allen Hamilton, Abt Associates, Oliver Wyman',
       'Anthem, Molina Healthcare, Humana',
       'Kforce, PageGroup, Robert Half',
       'DP Electric, Helix Electric, Wilson Electric', 'Adecco, Kforce',
       'Big O Tires, Les Schwab Tire Centers, Pep Boys',
       'Harris, Gogo, Inmarsat', 'TEKsystems, Aerotek',
       'Advance Auto Parts, AutoZone, NAPA Auto Parts',
       'Charles Schwab, Fidelity Investments, Edward Jones',
       'ComforceHealth, TEKsystems, Allegis Group',
       'GEICO, Allstate, State Farm',
       'NEXTGEN GLOBAL RESOURCES, Wavsys, TEKsystems',
       'MATRIX Resources, The Insource Group, TEKsystems',
       'Walmart, Walgreens, Express Scripts',
       'DrugDev , Bracket, Bioclinica', 'Covance, ICON',
       'Kforce, Insight Global, Volt Consulting Group',
       'Harvard University, Yale University, Princeton University',
       'UnitedHealth Group, Molina Healthcare, Centene',
       'Thermo Fisher Scientific, MilliporeSigma, Merck KGaA', 'Vaptech',
       'The Judge Group, Addison Group, PageGroup',
       'Chase, BB&T, SunTrust',
       'Lockheed Martin, Northrop Grumman, Airbus',
       'TEKsystems, CGI, SDLC Partners',
       'PathFinder Staffing, Juno Search Partners, Robert Half',
       'Aerotek, Kforce, Glotel', 'Pfizer, AstraZeneca, Merck',
       'Penn Medicine, Kimmel Cancer Center Jefferson, Abington Jefferson Health',
       'General Dynamics, Lockheed Martin',
       'BAE Systems USA, CACI International, General Dynamics Information Technology',
       'Infosys, Tata Consultancy Services, Wipro',
       'PetSmart, Walmart, Costco Wholesale',
       'Booz Allen Hamilton, Noblis, Deloitte',
       'SAIC, Leidos, Northrop Grumman',
       'Chenega Corporation, Chugach Alaska, ASRC Federal Holding Company',
       'PRA Group', 'Cornerstone OnDemand, Blackboard',
       'Sharp HealthCare, Scripps Health',
       'PRA Group, PRA Group (Canada)', 'Thermo Fisher Scientific, Roche',
       'Medtronic, Roche', 'Abbott, Siemens, Baxter', 'Biogen',
       'Square, PayPal, H&R Block',
       'Viejas Casino, Barona Casino, Pechanga Resort & Casino',
       'Forsythe Technology, ePlus', 'CDW, PCM, SHI International',
       'Tyler Technologies', 'ALDI, Tesco, Carrefour',
       'Accenture, Capgemini',
       'Ericsson-Worldwide, Huawei Technologies, Microsoft',
       'Kforce, Mitchell Martin, Insight Global',
       'FDIC, Office of the Comptroller of the Currency, SEC',
       'GATX, BNSF Railway', 'Infosys, Accenture, Capgemini',
       'Palo Alto Networks, NortonLifeLock, CrowdStrike',
       'Yardi Systems, AppFolio',
       'Marketing Werks, GMR Marketing, Anderson Merchandisers',
       'Arena, HCL Technologies, PTC',
       'Vivint Smart Home, Johnson Controls',
       'Mortgage Connect, Amrock, Title365',
       'SPX, Flowserve, Robbins & Myers',
       'Edelman, Burson-Marsteller, Weber Shandwick', 'Orthofix, Stryker',
       'Alliance Residential, Wood Partners, Trammell Crow Residential',
       'Avant, LendingClub, Prosper.com',
       'AIR Worldwide, EQECAT, Verisk Analytics',
       'Audi, BMW, Mercedes-Benz International',
       'TEKsystems, Collabera, Artech Information Systems',
       'STMicroelectronics, Fairchild Semiconductor, Infineon Technologies',
       'Insight Global, Pyramid Consulting, MATRIX Resources',
       'Salesforce, Oracle, Microsoft',
       'Mindtree, Happiest Minds Technologies, Altran Americas',
       'Mentor Graphics, Synopsys',
       'TEKsystems, Artech Information Systems, PDS Tech',
       'World Wide Technology, Astreya Partners, Taos',
       'Amgen, Baxter, Bristol Myers Squibb',
       'Optimal Solutions Integration, Capgemini',
       'TEKsystems, Akraya, Intelliswift', 'Amazon, Best Buy, Apple',
       'Skytron, STERIS, Hill-Rom', 'Chegg, StudyBlue',
       'Sutter Health, UCSF Medical Center and UCSF Benioff Children’s Hospitals, Kaiser Permanente',
       'InsWeb, Insure.com, Answer Financial', 'Aquent, 24 Seven Talent',
       'Palo Alto Networks, FireEye, Juniper Networks',
       'Lionbridge, SDL, TransPerfect',
       'Illumina, Thermo Fisher Scientific, Oxford Nanopore Technologies',
       'Nektar Therapeutics, Gilead Sciences, Theravance',
       'Amazon, Apple', 'Zocdoc, Sapphire Digital', 'OneSignal', 'Epic',
       'Interpublic Group, Omnicom, WPP', 'Bloomreach',
       'Google, Microsoft, Apple', 'Intuit',
       'Attain, Deloitte, Booz Allen Hamilton',
       'Boeing, Northrop Grumman, Raytheon Technologies',
       'American Eagle Outfitters, Ralph Lauren, J. Crew',
       'Aerotek, WinterWyman, Hollister Staffing', 'Robert Half, Kforce',
       'Cognizant Technology Solutions, EY, McKinsey & Company',
       'Accenture, IBM, Infosys',
       'Cognizant Technology Solutions, Accenture, IBM',
       'TireHub, National Tire Warehouse, Dealer Tire',
       'TEKMARK Global Solutions, Marlabs, IBM',
       'Intercontinental Exchange, Euronext, Nasdaq',
       'The Home Depot, Amazon, Walmart',
       'Midas, Monro Auto Service and Tire Centers',
       'C.H. Robinson, Transplace',
       'Blizzard Entertainment, Riot Games, Electronic Arts', 'LinkedIn',
       'Pusher, Firebase', 'Amazon, Google, Microsoft',
       'Paxata, Datameer, Informatica', 'UserZoom, Validately',
       'Stanford Health Care, Dignity Health, Sutter Health',
       'Zillow, Trulia, Coldwell Banker', 'Facebook, Google, Pinterest',
       'Silicon Valley Bank, City National Bank (Texas)',
       'Illumina, Agilent Technologies, Roche',
       'NortonLifeLock, McAfee, Verisign',
       'Collabera, Mitchell Martin, The Judge Group',
       'Bank of America, Wells Fargo, U.S. Bank',
       'Thermo Fisher Scientific, Abbott, Ortho Clinical Diagnostics',
       'Redis Labs, GridGain', 'Nurx', 'Fidelity Investments, Vanguard',
       'Kaiser Permanente, UC Davis Health, Dignity Health',
       'Mu Sigma, ZS Associates, Fractal', 'Accenture, Deloitte, IBM',
       'Spectrum Brands, Scotts Miracle-Gro, Newell Brands',
       'CUNA Mutual, SWBC, Overby-Seawell',
       'Apex Systems, Kforce, Robert Half', 'Lionbridge, Pole To Win',
       'DHL Global Forwarding, Freight, DB Schenker, Panalpina',
       'SDL, Keywords Studios, TransPerfect', 'Google, Amazon, Apple',
       "Sam's Club, BJ's Wholesale Club", 'Zillow, Trulia',
       'WeDo technologies, Intec Telecom, Amdocs',
       "Seattle Children's, Center for Infectious Disease Research, University of Washington",
       'Cognizant Technology Solutions, Tata Consultancy Services, Accenture',
       'Equinix, Digital Realty, CyrusOne',
       'Cognizant Technology Solutions, Infosys, HCL Technologies',
       'Morningstar, Value Line, Bankrate',
       'Checkout 51, RetailMeNot, shopkick',
       'BNY Mellon, DTCC, Computershare', 'Lennar, Meritage Homes',
       'Randstad, Kelly', 'AT&T, Verizon', 'Premier, Inc., Vizient',
       'Avnet, Ingram Micro, Tech Data',
       'Centura Health, HealthONE, Denver Health and Hospital Authority'],
      dtype=object)

In [116]:
df.head()

,Job Title,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Estimate($)
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 - 500,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),No Compititors,True,$37K-$66K
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),No Compititors,False,$37K-$66K
2,"Senior Data Analyst, Insights & Analytics Team...",We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 - 5000,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,False,$37K-$66K
3,Data Analyst,Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 - 500,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),No Compititors,False,$37K-$66K
4,Reporting Data Analyst,ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 - 1000,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True,$37K-$66K

In [118]:
df.Location.unique()

array(['New York, NY', 'Jersey City, NJ', 'Brooklyn, NY', 'Weehawken, NJ',
       'Florham Park, NJ', 'Manhasset, NY', 'Queens Village, NY',
       'Haworth, NJ', 'Fort Lee, NJ', 'Bronx, NY', 'Newark, NJ',
       'Lake Success, NY', 'Summit, NJ', 'Berkeley Heights, NJ',
       'Essex Fells, NJ', 'South Plainfield, NJ', 'Franklin Lakes, NJ',
       'Mount Vernon, NY', 'Secaucus, NJ', 'Woodbridge, NJ',
       'Parsippany, NJ', 'Whippany, NJ', 'Hoboken, NJ', 'West Orange, NJ',
       'Iselin, NJ', 'Montvale, NJ', 'Salt Lake City, UT', 'Lehi, UT',
       'Draper, UT', 'American Fork, UT', 'Reedley, CA', 'Hanford, CA',
       'Hampton, VA', 'Norfolk, VA', 'Portsmouth, VA', 'Smithfield, VA',
       'Suffolk, VA', 'Yorktown, VA', 'Chesapeake, VA', 'Fort Eustis, VA',
       'Gainesville, FL', 'Alachua, FL', 'El Segundo, CA',
       'Santa Monica, CA', 'Los Angeles, CA', 'Hermosa Beach, CA',
       'Burbank, CA', 'Culver City, CA', 'Glendale, CA', 'Inglewood, CA',
       'Venice, CA', 'Pasadena, CA', 'Cerritos, CA', 'Beverly Hills, CA',
       'Northridge, CA', 'Long Beach, CA', 'Brea, CA',
       'Woodland Hills, CA', 'Marina del Rey, CA', 'Torrance, CA',
       'Alhambra, CA', 'Azusa, CA', 'City of Industry, CA', 'Arcadia, CA',
       'Gardena, CA', 'Pico Rivera, CA', 'Whittier, CA', 'Chicago, IL',
       'Downers Grove, IL', 'Broadview, IL', 'Woodridge, IL',
       'Rolling Meadows, IL', 'Deerfield, IL', 'Northlake, IL',
       'Northbrook, IL', 'Des Plaines, IL', 'Itasca, IL', 'Evanston, IL',
       'Oak Brook, IL', 'Maywood, IL', 'Northfield, IL', 'Glenview, IL',
       'Elk Grove Village, IL', 'Houston, TX', 'Stafford, TX',
       'Pearland, TX', 'Pasadena, TX', 'Sugar Land, TX', 'Tempe, AZ',
       'Phoenix, AZ', 'Scottsdale, AZ', 'Glendale, AZ', 'Chandler, AZ',
       'DC Ranch, AZ', 'Mesa, AZ', 'King of Prussia, PA',
       'Plymouth Meeting, PA', 'Blue Bell, PA', 'Fort Washington, PA',
       'Philadelphia, PA', 'Wilmington, DE', 'Malvern, PA', 'Camden, NJ',
       'Feasterville Trevose, PA', 'Radnor, PA', 'West Conshohocken, PA',
       'Bensalem, PA', 'Horsham, PA', 'Exton, PA', 'Wayne, PA',
       'Paoli, PA', 'Conshohocken, PA', 'Mount Laurel, NJ',
       'Ridley Park, PA', 'West Chester, PA', 'Berwyn, PA',
       'Boothwyn, PA', 'West Point, PA', 'Marlton, NJ', 'San Antonio, TX',
       'Lackland AFB, TX', 'San Diego, CA', 'El Cajon, CA', 'Plano, TX',
       'Allen, TX', 'Arlington, TX', 'Dallas, TX', 'Irving, TX',
       'Richardson, TX', 'Grapevine, TX', 'Lewisville, TX', 'Addison, TX',
       'Carrollton, TX', 'Coppell, TX', 'Farmers Branch, TX',
       'Newark, CA', 'Santa Clara, CA', 'Redwood City, CA',
       'Cupertino, CA', 'Fremont, CA', 'San Jose, CA', 'Menlo Park, CA',
       'Palo Alto, CA', 'Mountain View, CA', 'Los Gatos, CA',
       'Sunnyvale, CA', 'Stanford, CA', 'East Palo Alto, CA',
       'Union City, CA', 'Milpitas, CA', 'Campbell, CA', 'Austin, TX',
       'Cedar Park, TX', 'Round Rock, TX', 'Jacksonville, FL',
       'Fort Worth, TX', 'Westlake, TX', 'Columbus, OH',
       'Westerville, OH', 'Dublin, OH', 'Charlotte, NC',
       'Mooresville, NC', 'Huntersville, NC', 'Fort Mill, SC',
       'Indian Trail, NC', 'San Francisco, CA', 'San Rafael, CA',
       'San Mateo, CA', 'Oakland, CA', 'Berkeley, CA', 'Burlingame, CA',
       'Foster City, CA', 'Marin City, CA', 'Daly City, CA',
       'South San Francisco, CA', 'Emeryville, CA', 'Novato, CA',
       'Millbrae, CA', 'San Ramon, CA', 'Hercules, CA', 'Alameda, CA',
       'Walnut Creek, CA', 'Carmel, IN', 'Indianapolis, IN',
       'Whitestown, IN', 'Jeffersonville, IN', 'Beech Grove, IN',
       'Redmond, WA', 'Seattle, WA', 'Issaquah, WA', 'Kent, WA',
       'Bellevue, WA', 'Kirkland, WA', 'Renton, WA', 'Athens, GA',
       'Burlingame, KS', 'Topeka, KS', 'Denver, CO', 'Centennial, CO',
       'Boulder, CO', 'Greenwood Village, Arapahoe, CO', 'Henderson, CO',
       'Englewood, CO', 'Lakewood, CO', 'Lone Tree, CO', 'Louisville, CO',
       'Broomfield, CO', 'Aurora, CO', 'Littleton, CO'], dtype=object)

In [119]:
df.head(2)

,Job Title,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply,Salary Estimate($)
0,"Data Analyst, Center on Immigration and Justic...",Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 - 500,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),No Compititors,True,$37K-$66K
1,Quality Data Analyst,Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),No Compititors,False,$37K-$66K

In [120]:
df.dtypes

Job Title              object
Job Description        object
Rating                float64
Company Name           object
Location               object
Headquarters           object
Size                   object
Founded                 int64
Type of ownership      object
Industry               object
Sector                 object
Revenue                object
Competitors            object
Easy Apply               bool
Salary Estimate($)     object
dtype: object